name: ml2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - geopandas
  - rasterio
  - xarray
  - scipy
  - jupyterlab
  - ipywidgets
  - flask
  - ipython
  - tifffile
  - hdf5
  - zlib
  - protobuf
  - grpcio
  - typing-extensions
  - pillow
  - boto3
  - botocore
  - pyproj
  - pyqt
  - fiona
  - shapely
  - gdal
  - ca-certificates
  - pip
  - pip:
      - leafmap
      - ipyleaflet
      - branca
      - plotly
      - rioxarray
      - whitebox
      - whiteboxgui
      - fastkml
      - psygnal
      - jupyter-leaflet
      - tenacity
      - geojson
      - pyshp
      - scikit-image
      - sympy
      - xarray
      - anywidget
      - tqdm
